export const GENERATE_PALETTE = 'GENERATE_PALETTE';
export const UPDATE_PALETTE = 'UPDATE_PALETTE';
export const RETRIEVE_PROJECTS = 'RETRIEVE_PROJECTS';
export const ADD_PALETTE = 'ADD_PALETTE';
export const ADD_PROJECT = 'ADD_PROJECT';
export const REMOVE_PALETTE = 'REMOVE_PALETTE';